<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Engine.Audio.OpenAL\Engine.Audio.OpenAL.csproj" />
    <ProjectReference Include="..\Engine.Audio\Engine.Audio.csproj" />
    <ProjectReference Include="..\Engine.Core\Engine.Core.csproj" />
    <ProjectReference Include="..\Engine.ECS\Engine.ECS.csproj" />
    <ProjectReference Include="..\Engine.Graphics.OpenGL\Engine.Graphics.OpenGL.csproj" />
    <ProjectReference Include="..\Engine.Graphics\Engine.Graphics.csproj" />
    <ProjectReference Include="..\Engine.Input\Engine.Input.csproj" />
    <ProjectReference Include="..\Engine.Physics\Engine.Physics.csproj" />
    <ProjectReference Include="..\Engine.Runtime\Engine.Runtime.csproj" />
    <ProjectReference Include="..\Engine.Simulations\Engine.Simulations.csproj" />
    <ProjectReference Include="..\Engine.Tooling\Engine.Tooling.csproj" />
    <ProjectReference Include="..\Engine.UI\Engine.UI.csproj" />
    <ProjectReference Include="..\Engine.World\Engine.Worlds.csproj" />
    <ProjectReference Include="..\Engine\Engine.Runtime.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\Textures\" />
    <Folder Include="Assets\Audio\" />
    <Folder Include="Rendering\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\Audio\test.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Fonts\ARIAL.TTF">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Sounds\smoke.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Textures\test.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
