<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Engine.Core\Engine.Core.csproj" />
    <ProjectReference Include="..\Engine.ECS\Engine.ECS.csproj" />
    <ProjectReference Include="..\Engine.Graphics\Engine.Graphics.csproj" />
    <ProjectReference Include="..\Engine.Input\Engine.Input.csproj" />
    <ProjectReference Include="..\Engine.Physics\Engine.Physics.csproj" />
    <ProjectReference Include="..\Engine.World\Engine.Worlds.csproj" />
  </ItemGroup>

</Project>
