<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="Silk.NET.OpenAL.Soft.Native" Version="1.23.1" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Engine.Audio.OpenAL\Engine.Audio.OpenAL.csproj" />
    <ProjectReference Include="..\Engine.Audio\Engine.Audio.csproj" />
    <ProjectReference Include="..\Engine.Core\Engine.Core.csproj" />
    <ProjectReference Include="..\Engine.ECS\Engine.ECS.csproj" />
    <ProjectReference Include="..\Engine.Graphics.OpenGL\Engine.Graphics.OpenGL.csproj" />
    <ProjectReference Include="..\Engine.Graphics\Engine.Graphics.csproj" />
    <ProjectReference Include="..\Engine.Input\Engine.Input.csproj" />
    <ProjectReference Include="..\Engine.Jobs\Engine.Jobs.csproj" />
    <ProjectReference Include="..\Engine.Memory\Engine.Memory.csproj" />
    <ProjectReference Include="..\Engine.Networking\Engine.Networking.csproj" />
    <ProjectReference Include="..\Engine.Runtime\Engine.Runtime.csproj" />
    <ProjectReference Include="..\Engine.Serialization\Engine.Serialization.csproj" />
    <ProjectReference Include="..\Engine.Simulations\Engine.Simulations.csproj" />
    <ProjectReference Include="..\Engine.World\Engine.Worlds.csproj" />
    <ProjectReference Include="..\Game.Sandbox\Game.Sandbox.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
