<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Engine.Graphics._2D</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Engine.Animation\Engine.Animation.csproj" />
    <ProjectReference Include="..\Engine.Camera\Engine.Camera.csproj" />
    <ProjectReference Include="..\Engine.Graphics\Engine.Graphics.csproj" />
  </ItemGroup>

</Project>
